# Trajectory Test Configuration
# All spatial units in meters, time in seconds, angles in radians

/**:
  ros__parameters:
    circle_radius: 1.5
    circle_center_x: 0.0
    circle_center_y: 0.0
    circle_center_z: -1.5
    circle_init_phase: 3.1415926
    circle_times: 5
    circle_duration: 3.0
    ramp_up_time: 6.0
    ramp_down_time: 6.0
    timer_period: 0.01
